### ISSUE TITLE
yank kodi with clipboard content as default

### ISSUE THREAD

**Issue by gardouille** [NapoleonWils0n/ubuntu-bin#1]
Hi ! :) 

Don't know if you might be interested, but i added clipboard management to your yank script.

If no argument, the script try to get Youtube's url from clipboard content (`xclip`) and set it as default infile. No youtube url = exit with usage and error message.

Github doesn't allow .patch extension… And i was a little lazy to fork, create a PR,… for something that might be useless to you :þ
So, the patch with .txt ext.

[yank.patch.txt](https://github.com/NapoleonWils0n/ubuntu-bin/files/5725428/yank.patch.txt)

And yeah, i didn't update usage() ^^

**Comment by NapoleonWils0n** [comment]
hi mate

nice work

i wont include it in the script as i try to keep the moving parts to a minimum
and have the script do one job well rather than be like a swiss army knife with lots of functions

also xclip isnt installed by default

feel free to modify any of my scripts as you see fit to suit your neees

happy xmas
